print('**** Seja bem vindo! ****')
print('Aqui você consegue descobrir o Dobro, triplo e a raiz quadrada de um numero!')
n=float(input('Digite um numero inteiro: '))
d = round(n * 2)
t = round(n * 3)
r = n **(1/2)
print(f'O dobro será {d} o triplo será {t} a raiz quadrada será {r}')